(()=>{
const cfg=window.IVY_CONFIG||{}, ok=cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('YOUR_PROJECT'), client=ok?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const S={session:null,profile:null,tab:null,schedules:[],leaves:[],profiles:[],locations:[],audit:[],channel:null}; const $=id=>document.getElementById(id); const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); const today=()=>new Date().toLocaleDateString('sv-SE'); const month=()=>today().slice(0,7); const st=t=>t?.slice(0,5)||''; const toast=m=>{const x=$('toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2300)};
function authMsg(m){$('auth-message').textContent=m||''} function showAuth(){$('auth-view').classList.remove('hidden');$('app-view').classList.add('hidden')} function showApp(){$('auth-view').classList.add('hidden');$('app-view').classList.remove('hidden')}
async function init(){if(!ok){showAuth();return authMsg('請先設定 config.js 與 Supabase。')}let {data:{session}}=await client.auth.getSession();if(session)await enter(session);else showAuth();client.auth.onAuthStateChange((_e,s)=>{if(!s){S.session=S.profile=null;showAuth()}})}
$('login-form').onsubmit=async e=>{e.preventDefault();let {data,error}=await client.auth.signInWithPassword({email:$('login-email').value.trim(),password:$('login-password').value});if(error)return authMsg('帳號或密碼錯誤');await enter(data.session)};$('logout-btn').onclick=()=>client?.auth.signOut();
async function enter(session){S.session=session;let {data:p}=await client.from('profiles').select('*').eq('id',session.user.id).single();if(!p||!p.active){await client.auth.signOut();return authMsg('帳號不存在或已停用。')}S.profile=p;S.tab=p.role==='manager'?'today':'home';showApp();await refresh();sub();render();if(p.must_change_password)setTimeout(changePassword,true,100)}
async function refresh(){let a=`${month()}-01`,d=new Date(+month().slice(0,4),+month().slice(5,7),0).toLocaleDateString('sv-SE');let qs=[client.from('schedules').select('*,employee:profiles!schedules_employee_id_fkey(id,full_name,department)').gte('work_date',a).lte('work_date',d).order('work_date'),client.from('leave_requests').select('*,employee:profiles!leave_requests_employee_id_fkey(id,full_name,department)').gte('leave_date',a).lte('leave_date',d).order('leave_date',{ascending:false}),client.from('work_locations').select('*').eq('active',true).order('sort_order')];if(S.profile.role==='manager'){qs.push(client.from('profiles').select('*').order('active',{ascending:false}).order('full_name'));qs.push(client.from('schedule_audit_logs').select('*,actor:profiles!schedule_audit_logs_changed_by_fkey(full_name)').order('changed_at',{ascending:false}).limit(100))}let [s,l,w,p,aud]=await Promise.all(qs);S.schedules=s.data||[];S.leaves=l.data||[];S.locations=w.data||[];if(p)S.profiles=p.data||[];if(aud)S.audit=aud.data||[]}
function sub(){if(S.channel)client.removeChannel(S.channel);S.channel=client.channel('ivy-'+S.profile.company_id).on('postgres_changes',{event:'*',schema:'public',table:'schedules'},sync).on('postgres_changes',{event:'*',schema:'public',table:'leave_requests'},sync).subscribe()}async function sync(){await refresh();render()}
function nav(){let mgr=S.profile.role==='manager';let items=mgr?[['today','今日','⌂'],['sched','排班','▦'],['staff','員工','♟'],['audit','紀錄','≡'],['profile','我的','●']]:[['home','首頁','⌂'],['cal','班表','▦'],['leave','請假','□'],['profile','我的','●']];$('bottom-nav').innerHTML=items.map(([k,n,i])=>`<button class="nav-item ${S.tab===k?'active':''}" data-tab="${k}"><b>${i}</b>${n}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;render()})}
function render(){$('role-label').textContent=S.profile.role==='manager'?'艾維公司・主管端':'艾維公司・員工端';$('app-title').textContent=S.profile.full_name;nav();({home:empHome,cal:empCal,leave:empLeave,profile:profile,today:mgrToday,sched:mgrSched,staff:mgrStaff,audit:mgrAudit}[S.tab]||empHome)()}
const card=s=>`<div class="card"><div class="row"><div><div class="name">${esc(s.employee?.full_name||S.profile.full_name)}・${esc(s.shift_name)}</div><div class="meta">${esc(s.work_date)}　${st(s.start_time)}–${st(s.end_time)}</div></div></div><div class="meta">📍 ${esc(s.location||'未設定')}　📄 ${esc(s.task_note||'')}</div></div>`;
function empHome(){let s=S.schedules.find(x=>x.employee_id===S.profile.id&&x.work_date===today());$('app-body').innerHTML=`${S.profile.must_change_password?'<div class="first-login">首次登入請先修改密碼。</div>':''}<div class="card"><div class="card-title">今日班次</div><h2>${s?st(s.start_time)+'–'+st(s.end_time):'今日無排班'}</h2></div>${s?card(s):''}`}
function empCal(){$('app-body').innerHTML=`<div class="page-head"><h2>${month()} 班表</h2></div>${S.schedules.filter(x=>x.employee_id===S.profile.id).map(card).join('')||'<div class="card empty">本月無排班</div>'}`}
function empLeave(){$('app-body').innerHTML=`<div class="page-head"><h2>請假</h2><button id="leave-new" class="btn small primary">＋申請</button></div>${S.leaves.filter(x=>x.employee_id===S.profile.id).map(x=>`<div class="card"><b>${esc(x.leave_type)}</b><div class="meta">${x.leave_date}・${esc(x.reason||'')}</div><div>${x.status}</div></div>`).join('')}`;$('leave-new').onclick=leaveModal}
function profile(){$('app-body').innerHTML=`<div class="card"><h2>${esc(S.profile.full_name)}</h2><p>${esc(S.profile.department||'未分組')}</p><p>${esc(S.session.user.email)}</p><button id="pw" class="btn primary">修改密碼</button>${S.profile.role==='employee'?'<button id="push" class="btn dark" style="margin-top:8px">開啟手機背景推播</button>':''}</div>`;$('pw').onclick=()=>changePassword(false);if($('push'))$('push').onclick=enablePush}
function mgrToday(){let list=S.schedules.filter(x=>x.work_date===today());$('app-body').innerHTML=`<div class="page-head"><h2>今日班表</h2><span>${list.length} 人</span></div>${list.map(card).join('')||'<div class="card empty">今日無排班</div>'}`}
function mgrSched(){$('app-body').innerHTML=`<div class="page-head"><h2>排班管理</h2></div><div class="toolbar"><button id="batch" class="btn small primary">＋一次排多人</button><button id="copy-y" class="btn small secondary">複製昨日</button><button id="copy-w" class="btn small secondary">複製上週</button><button id="excel" class="btn small success">Excel 匯出</button><button id="loc" class="btn small dark">工作地點</button></div>${dragCalendar()}`;$('batch').onclick=batchModal;$('copy-y').onclick=()=>copySchedule(1);$('copy-w').onclick=()=>copySchedule(7);$('excel').onclick=exportExcel;$('loc').onclick=locationModal;bindDrag()}
function dragCalendar(){let [y,m]=month().split('-').map(Number),days=new Date(y,m,0).getDate(),first=new Date(y,m-1,1).getDay(),html=['日','一','二','三','四','五','六'].map(x=>`<div class="cal-head">${x}</div>`).join('');for(let i=0;i<first;i++)html+='<div></div>';for(let d=1;d<=days;d++){let dt=`${month()}-${String(d).padStart(2,'0')}`,ss=S.schedules.filter(x=>x.work_date===dt);html+=`<div class="drag-day ${dt===today()?'today':''}" data-date="${dt}"><div class="drag-date">${d}</div>${ss.map(s=>`<div class="shift-token" draggable="true" data-id="${s.id}">${esc(s.employee?.full_name)} ${st(s.start_time)}</div>`).join('')}</div>`}return `<div class="card"><div class="drag-calendar">${html}</div></div><div class="notice">拖曳班次到另一日期即可移動；手機可長按後拖曳。</div>`}
function bindDrag(){let id=null;document.querySelectorAll('.shift-token').forEach(x=>x.ondragstart=()=>id=x.dataset.id);document.querySelectorAll('.drag-day').forEach(x=>{x.ondragover=e=>e.preventDefault();x.ondrop=async()=>{if(!id)return;let {error}=await client.from('schedules').update({work_date:x.dataset.date}).eq('id',id);if(error)return toast(error.message);toast('班次已移動');await notify('班表異動','您的班表日期已更新');await sync()}})}
function mgrStaff(){$('app-body').innerHTML=`<div class="page-head"><h2>員工管理</h2><button id="addstaff" class="btn small primary">＋新增員工</button></div><div class="tabs">${['全部','工程部','設計部','維養部'].map(x=>`<span class="chip">${x}</span>`).join('')}</div>${S.profiles.filter(p=>p.role==='employee').map(p=>`<div class="card employee-card ${p.active?'':'inactive'}"><div><b>${esc(p.full_name)}</b><div class="meta">${esc(p.department||'未分組')}・${esc(p.email||'')}</div></div><button class="btn small ${p.active?'warning':'success'}" data-toggle="${p.id}" data-active="${p.active}">${p.active?'停用':'啟用'}</button></div>`).join('')}`;$('addstaff').onclick=staffModal;document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleStaff(b.dataset.toggle,b.dataset.active==='true'))}
function mgrAudit(){$('app-body').innerHTML=`<div class="page-head"><h2>排班異動紀錄</h2></div>${S.audit.map(a=>`<div class="card audit-row"><b>${esc(a.actor?.full_name||'系統')}</b> ${esc(a.action)} 班表<br>${new Date(a.changed_at).toLocaleString('zh-TW')}・${esc(a.work_date||'')}</div>`).join('')||'<div class="card empty">尚無紀錄</div>'}`}
function modal(title,body){$('modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="page-head"><h3>${title}</h3><button id="mc" class="ghost-btn">關閉</button></div>${body}</div></div>`;$('mc').onclick=()=>$('modal-root').innerHTML=''}
function leaveModal(){modal('申請請假',`<form id="lf" class="form-grid"><label>假別<select id="lt"><option>特別休假</option><option>事假</option><option>病假</option></select></label><label>日期<input id="ld" type="date" required></label><label>事由<textarea id="lr"></textarea></label><button class="btn primary">送出</button></form>`);$('lf').onsubmit=async e=>{e.preventDefault();let {error}=await client.from('leave_requests').insert({company_id:S.profile.company_id,employee_id:S.profile.id,leave_type:$('lt').value,leave_date:$('ld').value,reason:$('lr').value,status:'pending'});if(error)return toast(error.message);$('modal-root').innerHTML='';await sync()}}
function batchModal(){let em=S.profiles.filter(p=>p.role==='employee'&&p.active);modal('一次排多人',`<form id="bf" class="form-grid"><div class="check-grid">${em.map(p=>`<label class="check-item"><input type="checkbox" name="emp" value="${p.id}">${esc(p.full_name)}・${esc(p.department||'')}</label>`).join('')}</div><label>日期<input id="bd" type="date" value="${today()}" required></label><div class="grid2"><label>開始<input id="bs" type="time" value="08:00"></label><label>結束<input id="be" type="time" value="17:00"></label></div><label>工作地點<select id="bl"><option value="">未設定</option>${S.locations.map(x=>`<option>${esc(x.name)}</option>`).join('')}</select></label><label>工作任務<textarea id="bt"></textarea></label><button class="btn primary">建立班表</button></form>`);$('bf').onsubmit=async e=>{e.preventDefault();let ids=[...document.querySelectorAll('input[name=emp]:checked')].map(x=>x.value);if(!ids.length)return toast('請選員工');let rows=ids.map(id=>({company_id:S.profile.company_id,employee_id:id,work_date:$('bd').value,start_time:$('bs').value,end_time:$('be').value,shift_name:'日班',location:$('bl').value||null,task_note:$('bt').value||null,created_by:S.profile.id}));let {error}=await client.from('schedules').insert(rows);if(error)return toast(error.message);$('modal-root').innerHTML='';await notify('新班表通知',`${$('bd').value} 班表已建立`,ids);await sync()}}
async function copySchedule(days){let dest=today(),src=new Date(dest+'T12:00:00');src.setDate(src.getDate()-days);src=src.toLocaleDateString('sv-SE');let rows=S.schedules.filter(x=>x.work_date===src);if(!rows.length)return toast('來源日期沒有班表');let out=rows.map(x=>({company_id:S.profile.company_id,employee_id:x.employee_id,work_date:dest,start_time:x.start_time,end_time:x.end_time,shift_name:x.shift_name,location:x.location,tools_note:x.tools_note,task_note:x.task_note,created_by:S.profile.id}));let {error}=await client.from('schedules').upsert(out,{onConflict:'employee_id,work_date,start_time',ignoreDuplicates:true});if(error)return toast(error.message);toast(`已複製 ${rows.length} 筆到今天`);await notify('班表更新','主管已複製班表');await sync()}
function exportExcel(){if(!window.XLSX)return toast('Excel 模組載入失敗');let rows=S.schedules.map(s=>({日期:s.work_date,員工:s.employee?.full_name,部門:s.employee?.department,開始:st(s.start_time),結束:st(s.end_time),班別:s.shift_name,地點:s.location||'',任務:s.task_note||'',工具:s.tools_note||''}));let ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'班表');XLSX.writeFile(wb,`艾維班表_${month()}.xlsx`)}
function locationModal(){modal('工作地點快速選擇',`<form id="locf" class="form-grid"><label>新增地點<input id="locn" required placeholder="例如：星巴克黎明福科門市"></label><button class="btn primary">新增</button></form>${S.locations.map(x=>`<div class="card">${esc(x.name)}</div>`).join('')}`);$('locf').onsubmit=async e=>{e.preventDefault();let {error}=await client.from('work_locations').insert({company_id:S.profile.company_id,name:$('locn').value.trim()});if(error)return toast(error.message);await refresh();locationModal()}}
function staffModal(){modal('新增員工',`<form id="sf" class="form-grid"><label>姓名<input id="sn" required></label><label>Email<input id="se" type="email" required></label><label>員工編號<input id="sno"></label><label>部門<select id="sd"><option>工程部</option><option>設計部</option><option>維養部</option></select></label><label>初始密碼<input id="sp" type="password" minlength="8" required></label><button class="btn primary">建立帳號</button></form>`);$('sf').onsubmit=async e=>{e.preventDefault();let {data,error}=await client.functions.invoke('admin-create-user',{body:{full_name:$('sn').value,email:$('se').value,employee_no:$('sno').value,department:$('sd').value,password:$('sp').value}});if(error||data?.error)return toast(data?.error||error.message);toast('員工帳號已建立');$('modal-root').innerHTML='';await sync()}}
async function toggleStaff(id,active){let {error}=await client.from('profiles').update({active:!active}).eq('id',id);if(error)return toast(error.message);toast(active?'員工已停用':'員工已啟用');await sync()}
function changePassword(forced){modal(forced?'首次登入：設定新密碼':'修改密碼',`<form id="pwf" class="form-grid"><label>新密碼<input id="npw" type="password" minlength="8" required></label><label>再次輸入<input id="cpw" type="password" minlength="8" required></label><button class="btn primary">儲存新密碼</button></form>`);if(forced)$('mc').style.display='none';$('pwf').onsubmit=async e=>{e.preventDefault();if($('npw').value!==$('cpw').value)return toast('兩次密碼不同');let {error}=await client.auth.updateUser({password:$('npw').value});if(error)return toast(error.message);await client.from('profiles').update({must_change_password:false}).eq('id',S.profile.id);S.profile.must_change_password=false;$('modal-root').innerHTML='';toast('密碼已更新')}}
function b64(s){let p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),r=atob(b),a=new Uint8Array(r.length);for(let i=0;i<r.length;i++)a[i]=r.charCodeAt(i);return a}
async function enablePush(){if(!('serviceWorker'in navigator)||!('PushManager'in window))return toast('此裝置不支援背景推播');if(!cfg.VAPID_PUBLIC_KEY||cfg.VAPID_PUBLIC_KEY.includes('YOUR_'))return toast('尚未設定 VAPID 公鑰');let perm=await Notification.requestPermission();if(perm!=='granted')return toast('未允許通知');let reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(cfg.VAPID_PUBLIC_KEY)});let {error}=await client.from('push_subscriptions').upsert({company_id:S.profile.company_id,user_id:S.profile.id,endpoint:sub.endpoint,subscription:sub.toJSON()},{onConflict:'endpoint'});if(error)return toast(error.message);toast('背景推播已開啟')}
async function notify(title,body,user_ids){try{await client.functions.invoke('send-push',{body:{company_id:S.profile.company_id,user_ids,title,body}})}catch(e){}}
init();
})();
