(()=>{
const cfg=window.IVY_CONFIG||{}, configured=cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('YOUR_PROJECT')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('YOUR_');
const client=configured?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const S={session:null,profile:null,tab:null,schedules:[],leaves:[],profiles:[],availability:[],audit:[],channel:null,monthOffset:0};
const $=id=>document.getElementById(id), esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const iso=d=>{let y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}, today=()=>iso(new Date());
const addMonths=(d,n)=>new Date(d.getFullYear(),d.getMonth()+n,1), monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`, viewMonth=()=>addMonths(new Date(),S.monthOffset);
const st=t=>t?.slice(0,5)||'', toast=m=>{let x=$('toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)};
function authMsg(m){$('auth-message').textContent=m||''} function showAuth(){$('auth-view').classList.remove('hidden');$('app-view').classList.add('hidden')} function showApp(){$('auth-view').classList.add('hidden');$('app-view').classList.remove('hidden')}
async function init(){if(!configured){showAuth();return authMsg('請先設定 config.js 與 Supabase。')}let {data:{session}}=await client.auth.getSession();if(session)await enter(session);else showAuth();client.auth.onAuthStateChange((_e,s)=>{if(!s){S.session=S.profile=null;showAuth()}})}
$('login-form').onsubmit=async e=>{e.preventDefault();let {data,error}=await client.auth.signInWithPassword({email:$('login-email').value.trim(),password:$('login-password').value});if(error)return authMsg('帳號或密碼錯誤');await enter(data.session)};$('logout-btn').onclick=()=>client?.auth.signOut();
async function enter(session){S.session=session;let {data:p,error}=await client.from('profiles').select('*').eq('id',session.user.id).single();if(error||!p||!p.active){await client.auth.signOut();return authMsg('帳號不存在或已停用。')}S.profile=p;S.tab=p.role==='manager'?'today':'home';showApp();await refresh();subscribe();render();if(p.must_change_password)setTimeout(()=>changePassword(true),100)}
function range(){let start=addMonths(new Date(),-1),end=addMonths(new Date(),4);return [iso(start),iso(new Date(end.getFullYear(),end.getMonth(),0))]}
async function refresh(){let [a,b]=range();let qs=[
 client.from('schedules').select('*,employee:profiles!schedules_employee_id_fkey(id,full_name,department)').gte('work_date',a).lte('work_date',b).order('work_date'),
 client.from('leave_requests').select('*,employee:profiles!leave_requests_employee_id_fkey(id,full_name,department)').gte('leave_date',a).lte('leave_date',b).order('created_at',{ascending:false}),
 client.from('work_availability').select('*').gte('work_date',a).lte('work_date',b)
];if(S.profile.role==='manager'){qs.push(client.from('profiles').select('*').order('active',{ascending:false}).order('full_name'));qs.push(client.from('schedule_audit_logs').select('*,actor:profiles!schedule_audit_logs_changed_by_fkey(full_name),employee:profiles!schedule_audit_logs_employee_id_fkey(full_name)').order('changed_at',{ascending:false}).limit(200))}
let [s,l,av,p,aud]=await Promise.all(qs);S.schedules=s.data||[];S.leaves=l.data||[];S.availability=av.data||[];if(p)S.profiles=p.data||[];if(aud)S.audit=aud.data||[]}
function subscribe(){if(S.channel)client.removeChannel(S.channel);S.channel=client.channel('ivy-live-'+S.profile.company_id)
 .on('postgres_changes',{event:'*',schema:'public',table:'schedules'},sync)
 .on('postgres_changes',{event:'*',schema:'public',table:'leave_requests'},sync)
 .on('postgres_changes',{event:'*',schema:'public',table:'work_availability'},sync).subscribe()}
async function sync(){await refresh();render()}
function nav(){let mgr=S.profile.role==='manager';let items=mgr?[['today','今日','⌂'],['sched','排班','▦'],['audit','紀錄','≡'],['profile','我的','●']]:[['home','首頁','⌂'],['cal','班表','▦'],['leave','請假','□'],['profile','我的','●']];$('bottom-nav').innerHTML=items.map(([k,n,i])=>`<button class="nav-item ${S.tab===k?'active':''}" data-tab="${k}"><b>${i}</b>${n}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;render()})}
function render(){$('role-label').textContent=S.profile.role==='manager'?'艾維公司・主管端':'艾維公司・員工端';$('app-title').textContent=S.profile.full_name;nav();({home:empHome,cal:empCal,leave:empLeave,profile:profile,today:mgrToday,sched:mgrSched,audit:mgrAudit}[S.tab]||empHome)()}
function monthNav(title='班表'){let d=viewMonth(),min=-1,max=3;return `<div class="month-nav"><button class="month-btn" id="prev-month" ${S.monthOffset<=min?'disabled':''}>‹</button><h2>${d.getFullYear()} 年 ${d.getMonth()+1} 月 ${esc(title)}</h2><button class="month-btn" id="next-month" ${S.monthOffset>=max?'disabled':''}>›</button></div>`}
function bindMonthNav(){if($('prev-month'))$('prev-month').onclick=()=>{if(S.monthOffset>-1){S.monthOffset--;render()}};if($('next-month'))$('next-month').onclick=()=>{if(S.monthOffset<3){S.monthOffset++;render()}}}
function calendar(renderDay){let d=viewMonth(),y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),first=new Date(y,m,1).getDay(),h=['日','一','二','三','四','五','六'].map(x=>`<div class="cal-head">${x}</div>`).join('');for(let i=0;i<first;i++)h+='<div class="calendar-blank"></div>';for(let n=1;n<=days;n++){let dt=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;h+=renderDay(dt,n)}return `<div class="calendar">${h}</div>`}
function empHome(){let s=S.schedules.find(x=>x.employee_id===S.profile.id&&x.work_date===today());$('app-body').innerHTML=`${S.profile.must_change_password?'<div class="first-login">首次登入請先修改密碼。</div>':''}<div class="page-head"><h2>今日班次</h2></div>${s?`<div class="card hero"><div class="card-title">今天工作地點</div><div class="today-location">📍 ${esc(s.location||'未設定')}</div><div class="today-reminder"><b>工作提醒</b><br>${esc(s.task_note||'目前沒有工作提醒')}</div></div>`:'<div class="card empty">今天沒有排班</div>'}`}
function empCal(){$('app-body').innerHTML=`${monthNav('班表')}<div class="notice">點選日期可切換「可以上班」。綠色日期代表你已回報可上班；有排班的日期會顯示工作地點。</div><div class="card">${calendar((dt,n)=>{let a=S.availability.some(x=>x.employee_id===S.profile.id&&x.work_date===dt&&x.available),s=S.schedules.find(x=>x.employee_id===S.profile.id&&x.work_date===dt);return `<button class="cal-day selectable ${a?'available':''} ${s?'has-shift':''}" data-avail="${dt}"><span class="day-no">${n}</span>${a?'<span class="cal-label">可上班</span>':''}${s?`<span class="cal-job">${esc(s.location||'已排班')}</span>`:''}</button>`})}</div>`;bindMonthNav();document.querySelectorAll('[data-avail]').forEach(b=>b.onclick=()=>toggleAvailability(b.dataset.avail))}
async function toggleAvailability(dt){let row=S.availability.find(x=>x.employee_id===S.profile.id&&x.work_date===dt);if(row){let {error}=await client.from('work_availability').delete().eq('id',row.id);if(error)return toast(error.message)}else{let {error}=await client.from('work_availability').insert({company_id:S.profile.company_id,employee_id:S.profile.id,work_date:dt,available:true});if(error)return toast(error.message)}await sync()}
function statusText(s){return s==='approved'?'已同意':s==='rejected'?'未同意':'待主管審核'}
function empLeave(){$('app-body').innerHTML=`<div class="page-head"><h2>請假</h2><button id="leave-new" class="btn small primary">＋申請</button></div>${S.leaves.filter(x=>x.employee_id===S.profile.id).map(x=>`<div class="card"><div class="row"><b>${esc(x.leave_type)}</b><span class="pill ${x.status==='approved'?'green':x.status==='rejected'?'red':'orange'}">${statusText(x.status)}</span></div><div class="meta">${x.leave_date}・${esc(x.reason||'')}</div></div>`).join('')||'<div class="card empty">目前沒有請假紀錄</div>'}`;$('leave-new').onclick=leaveModal}
function profile(){let staff=S.profile.role==='manager'?`<div class="section-label">員工管理</div><div class="card"><button id="addstaff" class="btn primary">＋新增員工</button></div>${S.profiles.filter(p=>p.role==='employee').map(p=>`<div class="card employee-card ${p.active?'':'inactive'}"><div><b>${esc(p.full_name)}</b><div class="meta">${esc(p.department||'未分組')}・${esc(p.email||'')}</div></div><button class="btn small ${p.active?'warning':'success'}" data-toggle="${p.id}" data-active="${p.active}">${p.active?'停用':'啟用'}</button></div>`).join('')}`:'';$('app-body').innerHTML=`<div class="card"><h2>${esc(S.profile.full_name)}</h2><p>${esc(S.profile.department||'未分組')}</p><p>${esc(S.session.user.email)}</p><button id="pw" class="btn primary">修改密碼</button><button id="push" class="btn dark" style="margin-top:8px;width:100%">開啟手機背景推播</button><div id="push-help" class="subtle" style="margin-top:8px"></div></div>${staff}`;$('pw').onclick=()=>changePassword(false);$('push').onclick=enablePush;pushStatus();if($('addstaff'))$('addstaff').onclick=staffModal;document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleStaff(b.dataset.toggle,b.dataset.active==='true'))}
async function pushStatus(){let el=$('push-help');if(!el)return;if(!window.isSecureContext)return el.textContent='推播需要 HTTPS。';if(!('serviceWorker'in navigator)||!('PushManager'in window))return el.textContent='此瀏覽器不支援 Web Push。iPhone 請先「加入主畫面」後從 App 開啟。';let reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();el.textContent=sub?'✓ 此裝置已啟用背景推播':'尚未在此裝置啟用推播。'}
function mgrToday(){let list=S.schedules.filter(x=>x.work_date===today());$('app-body').innerHTML=`<div class="page-head"><h2>今日班表</h2><span>${list.length} 人</span></div>${list.map(s=>scheduleCard(s,true)).join('')||'<div class="card empty">今日無排班</div>'}`}
function scheduleCard(s,edit=false){return `<div class="card"><div class="row"><div><div class="name">${esc(s.employee?.full_name||'')}</div><div class="meta">${esc(s.work_date)}</div></div>${edit?`<button class="btn small secondary" data-edit="${s.id}">修改</button>`:''}</div><div class="meta">📍 ${esc(s.location||'未設定')}</div><div class="meta">📄 ${esc(s.task_note||'無工作提醒')}</div></div>`}
function mgrSched(){$('app-body').innerHTML=`${monthNav('排班')}<div class="toolbar"><button id="batch" class="btn small primary">＋一次排多人</button><button id="copy-y" class="btn small secondary">複製昨日</button><button id="copy-w" class="btn small secondary">複製上週</button><button id="excel" class="btn small success">Excel 匯出</button></div><div class="card">${calendar((dt,n)=>{let ss=S.schedules.filter(x=>x.work_date===dt);return `<div class="manager-day ${dt===today()?'today':''}" data-dropdate="${dt}"><span class="day-no">${n}</span>${ss.map(s=>`<button class="shift-token" draggable="true" data-id="${s.id}" data-edit="${s.id}">${esc(s.employee?.full_name)}<small>${esc(s.location||'')}</small></button>`).join('')}</div>`})}</div><div class="notice">點班次可修改；桌面瀏覽器也可拖曳到其他日期。手機請用「修改」選日期，穩定度較高。</div>`;bindMonthNav();$('batch').onclick=batchModal;$('copy-y').onclick=()=>copySchedule(1);$('copy-w').onclick=()=>copySchedule(7);$('excel').onclick=exportExcel;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();editSchedule(b.dataset.edit)});bindDrag()}
function bindDrag(){let id=null;document.querySelectorAll('.shift-token').forEach(x=>x.ondragstart=()=>id=x.dataset.id);document.querySelectorAll('[data-dropdate]').forEach(x=>{x.ondragover=e=>e.preventDefault();x.ondrop=async e=>{e.preventDefault();if(!id)return;let s=S.schedules.find(z=>z.id===id),{error}=await client.from('schedules').update({work_date:x.dataset.dropdate}).eq('id',id);if(error)return toast(error.message);await notify('班表異動',`您的班表已改到 ${x.dataset.dropdate}`,[s.employee_id]);toast('班次已移動');await sync()}})}
function mgrAudit(){let pending=S.leaves.filter(x=>x.status==='pending'),d=viewMonth(),mk=monthKey(d),emps=S.profiles.filter(p=>p.role==='employee'&&p.active);$('app-body').innerHTML=`<div class="page-head"><h2>紀錄</h2></div><div class="section-label">待審核假單 (${pending.length})</div>${pending.map(l=>`<div class="card"><div class="row"><div><b>${esc(l.employee?.full_name)}・${esc(l.leave_type)}</b><div class="meta">${l.leave_date}・${esc(l.reason||'')}</div></div><span class="pill orange">待審核</span></div><div class="actions"><button class="btn small success" data-leave="${l.id}" data-status="approved">同意請假</button><button class="btn small danger" data-leave="${l.id}" data-status="rejected">不同意</button></div></div>`).join('')||'<div class="card empty">目前沒有待審核假單</div>'}<div class="section-label">${mk} 員工出席統計</div>${emps.map(p=>{let n=S.schedules.filter(s=>s.employee_id===p.id&&s.work_date.startsWith(mk)).length;return `<div class="card attendance"><b>${esc(p.full_name)}</b><span>出席總天數 <strong>${n}</strong> 天</span></div>`}).join('')}<div class="section-label">排班異動紀錄</div>${S.audit.map(a=>`<div class="card audit-row"><b>${esc(a.actor?.full_name||'系統')}</b> ${a.action==='update'?'修改':a.action==='insert'?'新增':a.action==='delete'?'刪除':esc(a.action)} ${esc(a.employee?.full_name||'')} 班表<br>${new Date(a.changed_at).toLocaleString('zh-TW')}・${esc(a.work_date||'')}</div>`).join('')||'<div class="card empty">尚無異動紀錄</div>'}`;document.querySelectorAll('[data-leave]').forEach(b=>b.onclick=()=>reviewLeave(b.dataset.leave,b.dataset.status))}
async function reviewLeave(id,status){let l=S.leaves.find(x=>x.id===id),{error}=await client.from('leave_requests').update({status,reviewed_by:S.profile.id,reviewed_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);await notify(status==='approved'?'請假已同意':'請假未同意',`${l.leave_date} ${l.leave_type}：${status==='approved'?'主管已同意':'主管未同意'}`,[l.employee_id]);toast(status==='approved'?'已同意請假':'已標記未同意');await sync()}
function modal(title,body){$('modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="page-head"><h3>${title}</h3><button id="mc" class="ghost-btn modal-close">關閉</button></div>${body}</div></div>`;$('mc').onclick=()=>$('modal-root').innerHTML=''}
function leaveModal(){modal('申請請假',`<form id="lf" class="form-grid"><label>假別<select id="lt"><option>特別休假</option><option>事假</option><option>病假</option></select></label><label>日期<input id="ld" type="date" required></label><label>事由<textarea id="lr"></textarea></label><button class="btn primary">送出</button></form>`);$('lf').onsubmit=async e=>{e.preventDefault();let {error}=await client.from('leave_requests').insert({company_id:S.profile.company_id,employee_id:S.profile.id,leave_type:$('lt').value,leave_date:$('ld').value,reason:$('lr').value,status:'pending'});if(error)return toast(error.message);$('modal-root').innerHTML='';let managers=S.profiles.filter?.(p=>p.role==='manager').map(p=>p.id);await notify('新請假申請',`${S.profile.full_name} 提出 ${$('ld')?.value||''} 請假申請`,managers?.length?managers:undefined,true);toast('假單已送出主管端');await sync()}}
function batchModal(){let em=S.profiles.filter(p=>p.role==='employee'&&p.active);modal('一次排多人',`<form id="bf" class="form-grid"><div class="check-grid">${em.map(p=>`<label class="check-item"><input type="checkbox" name="emp" value="${p.id}">${esc(p.full_name)}・${esc(p.department||'')}</label>`).join('')}</div><label>日期<input id="bd" type="date" value="${today()}" required></label><label>工作地點<input id="bl" placeholder="可自由輸入，例如：星巴克黎明福科門市"></label><label>工作提醒<textarea id="bt" placeholder="今天需要注意的工作事項"></textarea></label><button class="btn primary">建立班表</button></form>`);$('bf').onsubmit=async e=>{e.preventDefault();let ids=[...document.querySelectorAll('input[name=emp]:checked')].map(x=>x.value);if(!ids.length)return toast('請選員工');let rows=ids.map(id=>({company_id:S.profile.company_id,employee_id:id,work_date:$('bd').value,start_time:'08:00',end_time:'17:00',shift_name:'日班',location:$('bl').value.trim()||null,task_note:$('bt').value.trim()||null,created_by:S.profile.id}));let {error}=await client.from('schedules').insert(rows);if(error)return toast(error.message);let dt=$('bd').value;$('modal-root').innerHTML='';await notify('新班表通知',`${dt} 班表已建立`,ids);toast('班表已建立');await sync()}}
function editSchedule(id){let s=S.schedules.find(x=>x.id===id);if(!s)return;modal('修改排班',`<form id="ef" class="form-grid"><label>員工<input value="${esc(s.employee?.full_name||'')}" disabled></label><label>日期<input id="ed" type="date" value="${s.work_date}" required></label><label>工作地點<input id="el" value="${esc(s.location||'')}" placeholder="自由輸入工作地點"></label><label>工作提醒<textarea id="et">${esc(s.task_note||'')}</textarea></label><button class="btn primary">儲存修改</button><button type="button" id="edel" class="btn danger">刪除此排班</button></form>`);$('ef').onsubmit=async e=>{e.preventDefault();let changes={work_date:$('ed').value,location:$('el').value.trim()||null,task_note:$('et').value.trim()||null},{error}=await client.from('schedules').update(changes).eq('id',id);if(error)return toast(error.message);$('modal-root').innerHTML='';await notify('班表內容已修改',`${changes.work_date}｜${changes.location||'工作地點未設定'}｜${changes.task_note||'無工作提醒'}`,[s.employee_id]);toast('修改已即時同步');await sync()};$('edel').onclick=async()=>{if(!confirm('確定刪除此排班？'))return;let {error}=await client.from('schedules').delete().eq('id',id);if(error)return toast(error.message);$('modal-root').innerHTML='';await notify('班表取消',`${s.work_date} 的班表已取消`,[s.employee_id]);await sync()}}
async function copySchedule(days){let dest=today(),src=new Date(dest+'T12:00:00');src.setDate(src.getDate()-days);src=iso(src);let rows=S.schedules.filter(x=>x.work_date===src);if(!rows.length)return toast('來源日期沒有班表');let out=rows.map(x=>({company_id:S.profile.company_id,employee_id:x.employee_id,work_date:dest,start_time:x.start_time,end_time:x.end_time,shift_name:x.shift_name,location:x.location,tools_note:x.tools_note,task_note:x.task_note,created_by:S.profile.id}));let {error}=await client.from('schedules').upsert(out,{onConflict:'employee_id,work_date,start_time',ignoreDuplicates:true});if(error)return toast(error.message);await notify('班表更新','主管已更新今天班表',rows.map(x=>x.employee_id));toast(`已複製 ${rows.length} 筆到今天`);await sync()}
function exportExcel(){if(!window.XLSX)return toast('Excel 模組載入失敗');let mk=monthKey(viewMonth()),rows=S.schedules.filter(s=>s.work_date.startsWith(mk)).map(s=>({日期:s.work_date,員工:s.employee?.full_name,部門:s.employee?.department,地點:s.location||'',工作提醒:s.task_note||''}));let ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'班表');XLSX.writeFile(wb,`艾維班表_${mk}.xlsx`)}
function staffModal(){modal('新增員工',`<form id="sf" class="form-grid"><label>姓名<input id="sn" required></label><label>Email<input id="se" type="email" required></label><label>員工編號<input id="sno"></label><label>部門<select id="sd"><option>工程部</option><option>設計部</option><option>維養部</option></select></label><label>初始密碼<input id="sp" type="password" minlength="8" required></label><button class="btn primary">建立帳號</button></form>`);$('sf').onsubmit=async e=>{e.preventDefault();let {data,error}=await client.functions.invoke('admin-create-user',{body:{full_name:$('sn').value,email:$('se').value,employee_no:$('sno').value,department:$('sd').value,password:$('sp').value}});if(error||data?.error)return toast(data?.error||error.message);toast('員工帳號已建立');$('modal-root').innerHTML='';await sync()}}
async function toggleStaff(id,active){let {error}=await client.from('profiles').update({active:!active}).eq('id',id);if(error)return toast(error.message);toast(active?'員工已停用':'員工已啟用');await sync()}
function changePassword(forced){modal(forced?'首次登入：設定新密碼':'修改密碼',`<form id="pwf" class="form-grid"><label>新密碼<input id="npw" type="password" minlength="8" required></label><label>再次輸入<input id="cpw" type="password" minlength="8" required></label><button class="btn primary">儲存新密碼</button></form>`);if(forced)$('mc').style.display='none';$('pwf').onsubmit=async e=>{e.preventDefault();if($('npw').value!==$('cpw').value)return toast('兩次密碼不同');let {error}=await client.auth.updateUser({password:$('npw').value});if(error)return toast(error.message);await client.from('profiles').update({must_change_password:false}).eq('id',S.profile.id);S.profile.must_change_password=false;$('modal-root').innerHTML='';toast('密碼已更新')}}
function b64(s){let p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),r=atob(b),a=new Uint8Array(r.length);for(let i=0;i<r.length;i++)a[i]=r.charCodeAt(i);return a}
async function enablePush(){try{if(!window.isSecureContext)return toast('推播需要 HTTPS');if(!('serviceWorker'in navigator)||!('PushManager'in window))return toast('iPhone 請先加入主畫面，再從 App 開啟推播');if(!cfg.VAPID_PUBLIC_KEY||cfg.VAPID_PUBLIC_KEY.includes('YOUR_'))return toast('config.js 尚未設定 VAPID_PUBLIC_KEY');let perm=await Notification.requestPermission();if(perm!=='granted')return toast('通知權限未允許，請到手機設定開啟');let reg=await navigator.serviceWorker.ready,old=await reg.pushManager.getSubscription(),sub=old||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(cfg.VAPID_PUBLIC_KEY)});let {error}=await client.from('push_subscriptions').upsert({company_id:S.profile.company_id,user_id:S.profile.id,endpoint:sub.endpoint,subscription:sub.toJSON()},{onConflict:'endpoint'});if(error)return toast(error.message);toast('背景推播已成功開啟');pushStatus()}catch(e){toast('推播開啟失敗：'+(e.message||e))}
async function notify(title,body,user_ids,managersOnly=false){try{await client.functions.invoke('send-push',{body:{company_id:S.profile.company_id,user_ids,title,body,managers_only:managersOnly}})}catch(e){}}
init();
})();